import {
    ColorSchemeScript,
    DirectionProvider,
    mantineHtmlProps,
    MantineProvider,
    type MantineThemeOverride,
} from "@mantine/core";
import "@mantine/core/styles.css";
import "@mantine/dates/styles.css";
import type { Metadata } from "next";
import { Inter } from "next/font/google";
import { FunctionComponent } from "react";
import "./globals.css";

export const customTheme: MantineThemeOverride = {
    primaryColor: "violet",
    primaryShade: 9,
};

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
    title: "Create Next App",
    description: "Generated by create next app",
};

interface RootLayoutProps {
    readonly children: React.ReactNode;
}

const RootLayout: FunctionComponent<RootLayoutProps> = ({ children }) => {
    return (
        <html dir="rtl" {...mantineHtmlProps}>
            <head>
                <ColorSchemeScript />
            </head>
            <body className={inter.className}>
                <DirectionProvider>
                    <MantineProvider theme={customTheme}>{children}</MantineProvider>
                </DirectionProvider>
            </body>
        </html>
    );
};

export default RootLayout;
